version: '3'

services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "25:25"
      - "4433"
      - "8080"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      - LETSENCRYPT_EMAIL=admin@example.com
      - LETSENCRYPT_HOST=mail.example.com
      - VIRTUAL_HOST=mail.example.com
      - HTTPS=OFF
      - HTTP_PORT=8080
      - HTTPS_PORT=4433
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/poste:/da
