version: '3'

services:
  mailserver:
    image: analogic/poste.io
    container_name: mailserver
    restart: unless-stopped
    ports:
      - "25:25"
      - "8443:443"
      - "8000:80"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      - LETSENCRYPT_EMAIL=admin@example.com
      - LETSENCRYPT_HOST=mail.example.com
      - VIRTUAL_HOST=mail.example.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/poste:/da
